name: Build & deploy Webapp

env:
  ARTIFACT_NAME: csye6225-webapp-${{ github.run_number }}.zip
  CODEDEPLOY_APPLICATIONNAME: codedeploymentApp
  CODEDEPLOY_APPLICATION_DEPLOYMENT_GROUP_NAME: deploymentGroup
  AWS_REGION: us-east-1

# it'll be push
on:
  pull_request:
    branches: [ master ]


jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: build with maven
        run: |
          echo "${{ env.ARTIFACT_NAME}}"
          pwd
          ls
          mvn package
          pwd
          ls -al
          ls -al target/

      - name:  Deployment artifacts
        run: |
          mkdir codedeploy_artifacts
          zip -r ${{env.ARTIFACT_NAME}} target/cloudcomputing-0.0.1-SNAPSHOT.war scripts/*.sh appspec.yml
          pwd
          ls -al
          mv ${{env.ARTIFACT_NAME}} codedeploy_artifacts/
          ls -al
          pwd
          cd codedeploy_artifacts
          pwd
          ls -al
          cd ..
          pwd
          ls -al


      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: copy artifacts to s3
        run: |
          aws s3 sync ./codedeploye_artifacts s3://${{ secrets.S3_CODE_DEPLOY_BUCKET }}

      - name: codedeploy api call
        run: |
          output=$(aws deploy push --application-name ${{ env.CODEDEPLOY_APPLICATIONNAME }} --output json --ignore-hidden-files --s3-location s3://${{ secrets.S3_CODE_DEPLOY_BUCKET }}/${{ env.ARTIFACT_NAME }} --source . --region ${{ env.AWS_REGION }})
          echo $output
          dId=$(echo $output | jq -r '.deploymentId')
          aws deploy wait deployment-success --deployment-id $dId




